name: 'dividend_aristocrats'
version: '1.0.0'

profile: 'dividend_aristocrats'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dividend_yield_lookback_years: 5
  min_consecutive_years: 25

models:
  dividend_aristocrats:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
